// File generated by FlutterFire CLI.
// ignore_for_file: type=lintt
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvdFkmCNggZFrThxoEdtGGWm4XxGqP33A',
    appId: '1:493732491371:web:1f23818782ed6d9fab812e',
    messagingSenderId: '493732491371',
    projectId: 'sidesa-mobile',
    authDomain: 'sidesa-mobile.firebaseapp.com',
    storageBucket: 'sidesa-mobile.firebasestorage.app',
    measurementId: 'G-8677G0WCYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnVWJNfiHi5vW3pYIyWtQkW0DJ63TyIxw',
    appId: '1:493732491371:android:d58927e6d29f2c7bab812e',
    messagingSenderId: '493732491371',
    projectId: 'sidesa-mobile',
    storageBucket: 'sidesa-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmDbD2TjPbRO2Wew5qYO2KSFAuFBuSBB0',
    appId: '1:493732491371:ios:b1ab6fc9fa179f50ab812e',
    messagingSenderId: '493732491371',
    projectId: 'sidesa-mobile',
    storageBucket: 'sidesa-mobile.firebasestorage.app',
    iosBundleId: 'com.example.sidesaMobile',
  );
}
